### PR TITLE
Additional property and fixed positions.

### PR DESCRIPTION
**Pull request by howmanysmall**
* Added property `ActionColor` to change the TextColor3 of the Action button.
* Fixed the positioning of the SnackbarPosition Enums.

image

### CODE REVIEW

**Comment by Validark** [comment]
Great idea for additions to Snackbar. A few things:

I am not sure if I am misinterpreting your image, but don't you have left and right on the improper sides?

Also I think `ActionColor` should probably be `ActionColor3`, since we have always specified that `Color` values are `Color3` in their name. `TextColor3`, `ImageColor3`, `PrimaryColor3`, etc.

**Comment by Validark** [comment]
This too? https://github.com/RoStrap/RoStrapUI/blob/8517521482c2f118a63514205d17d4e3dd6c32a6/Snackbar.lua#L221

**Comment by howmanysmall** [comment]
Updated.

**Comment by Validark** [comment]
Great! I will test this one more time tomorrow and hopefully merge it!

**Pull request merged**
